"""Add tool_issues table

Revision ID: f4b0192c4c6f
Revises: dffad158cd71
Create Date: 2025-08-20 11:38:32.618377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b0192c4c6f'
down_revision = 'dffad158cd71'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
